# Import

In [6]:

import numpy as np

# Lista

In [7]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Arreglo

In [9]:
arreglo = np.array(lista)
arreglo 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
type(arreglo)

numpy.ndarray

# Tipos de datos


In [11]:
arreglo.dtype

dtype('int32')

In [16]:
np.array(arreglo. dtype)

array(dtype('int32'), dtype=object)

In [17]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h2 style = "color= blue";><b>Funciones</b></h2>

In [19]:
arreglo_Num = np.arange(1,11)
arreglo_Num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
prom = np.mean(arreglo)
prom

5.5

In [23]:
mediana = np.median(arreglo)
mediana

5.5

In [24]:
uno = np.ones(100)
uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
cero = np.zeros(100)
cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
arreglo_Aleatorio = np.random.rand(10)
arreglo_Aleatorio

array([0.91873724, 0.26665865, 0.71632194, 0.14801622, 0.22290809,
       0.91586175, 0.25916539, 0.14837702, 0.77260468, 0.16001268])

In [33]:
matriz = np.random.rand(3,1)
matriz

array([[0.65964579],
       [0.01769203],
       [0.95865864]])

In [35]:
arreglo_random = np.random.rand(1,1001,10,10)
arreglo_random

array([[[[0.87802631, 0.86286781, 0.23331538, ..., 0.92751535,
          0.04804018, 0.25720649],
         [0.0732517 , 0.62174293, 0.60725541, ..., 0.45561686,
          0.68367902, 0.20171292],
         [0.06354297, 0.13098713, 0.94841126, ..., 0.89669482,
          0.3429369 , 0.36049275],
         ...,
         [0.83729971, 0.88896552, 0.85957277, ..., 0.02692884,
          0.26237032, 0.44438913],
         [0.54749562, 0.17331934, 0.98630208, ..., 0.94567401,
          0.81257372, 0.86644522],
         [0.17225075, 0.70191003, 0.2403344 , ..., 0.03333547,
          0.84660965, 0.45110861]],

        [[0.14913068, 0.83800935, 0.28903314, ..., 0.89588938,
          0.1286094 , 0.50369301],
         [0.33547103, 0.43003514, 0.81552583, ..., 0.47359426,
          0.28662952, 0.39996793],
         [0.90536692, 0.60800296, 0.91645387, ..., 0.79031971,
          0.09636059, 0.1521649 ],
         ...,
         [0.25337407, 0.85905097, 0.92970323, ..., 0.03080967,
          0.82858704, 0.0