In [1]:
import numpy as np 

<h4 style = "color: #fff">a)</h4>


In [2]:
consecutivo = np.array(range(1,11))
consecutivo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h4 style = "color: #fff">b)</h4>

In [40]:
Aleatorio = np.array(range(1,20))
Aleatorio = np.random.choice(Aleatorio, 10)
Aleatorio

array([14, 13, 16,  3, 15, 18, 14, 12, 13, 17])

<h4 style = "color: #fff">c)</h4>

In [41]:
Suma = consecutivo +  Aleatorio 
Suma

array([15, 15, 19,  7, 20, 24, 21, 20, 22, 27])

<h4 style = "color: #fff">d)</h4>

In [79]:
np.random.shuffle(Suma)
Suma

array([27, 15, 20, 22,  7, 19, 20, 21, 24, 15])

<h4 style = "color: #fff">e)</h4>

In [80]:
#1 Mediana
Mediana = np.median(Suma)
Mediana

20.0

In [81]:
#2 Promedio
Prom = np.mean(Suma)
Prom

19.0

In [82]:
#3 Valor maximo
np.argmax(Suma)

0

In [83]:
#4 Valor Minimo 
np.argmin(Suma) 


4

<h4 style = "color: #fff">f)<h4>

In [87]:
Matriz = Suma.reshape(2,5)
Matriz

array([[27, 15, 20, 22,  7],
       [19, 20, 21, 24, 15]])